### ISSUE TITLE
请问一下多久刷新一次？

### ISSUE THREAD

**Issue by Spturate** [Zfour/hexo-github-calendar#8]
我已经等了24个小时了好像还没有刷新，请问一下刷新时间要多久？

**Comment by Zfour** [comment]
你一定用的是旧版，请使用新版，也就是这个项目。 新版api是实时刷新的。 ------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年3月13日(星期六) 凌晨1:37
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Zfour/hexo-github-calendar] 请问一下多久刷新一次？ (#8)
